console.log('🔍 Verificación de variables de entorno para Render');
console.log('==================================================');
console.log('');
console.log('❌ PROBLEMA IDENTIFICADO:');
console.log('   La variable JWT_SECRET no está configurada en Render');
console.log('   Esto causa el error: "secretOrPrivateKey must have a value"');
console.log('');
console.log('✅ SOLUCIÓN:');
console.log('   1. Ve a https://dashboard.render.com');
console.log('   2. Selecciona tu servicio "foodmike"');
console.log('   3. Ve a la pestaña "Environment"');
console.log('   4. Agrega estas variables:');
console.log('');
console.log('   🔐 JWT_SECRET=tu-super-secret-jwt-key-aqui-muy-largo-y-seguro');
console.log('   🌐 CORS_ORIGIN=*');
console.log('   🔧 NODE_ENV=production');
console.log('   📊 PORT=10000');
console.log('');
console.log('💡 JWT_SECRET debe ser una cadena larga y aleatoria, por ejemplo:');
console.log('   JWT_SECRET=foodmike-super-secret-jwt-key-2024-production-secure-random-string-123456789');
console.log('');
console.log('⚠️ IMPORTANTE:');
console.log('   - Después de agregar las variables, haz redeploy del servicio');
console.log('   - El JWT_SECRET debe ser único y no compartirse');
console.log('');
console.log('🎯 RESULTADO ESPERADO:');
console.log('   - El registro de usuarios funcionará correctamente');
console.log('   - Los productos y categorías se cargarán sin problemas');
console.log('   - La autenticación JWT funcionará correctamente'); 